name: Sandbox

on:
  workflow_dispatch:

jobs:
  sandbox:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install requests

      - name: Run Sandbox
        run: |
          python sandbox.py